### ISSUE TITLE
Shortcut_AddChildBlock not working with Logseq 0.7.0

### ISSUE THREAD

**Issue by brunomiguel** [vyleung/logseq-quick-add-plugin#1] opened 2022-05-26 07:37 UTC
I installed this plugin's latest version in Logseq 0.7.0, changed the default **Shortcut_AddChildBlock** keybind to _ctrl+alt+enter_ because it has a conflict with the task creation/task status change keybind, but it doesn't create a child block. Even without changing the keybind, it would create a TODO and/or change the task status because that's a default keybind for the software.

**Comment by vyleung** [comment] 2022-05-26 07:43
have you tried refreshing Logseq after changing the shortcut? also, a current limitation of adding a new child block is that the parent block must have one or more existing child blocks

**Comment by nhan000** [comment] 2022-05-27 08:25
I can confirm that the `Shortcut_AddChildBlock` works for me. Windows Desktop 0.7.0. The limitation as vyleung has said is as follow (I like something more visual):

![image](https://user-images.githubusercontent.com/85216095/170661170-ef30687e-fad0-4f7d-8e0b-970629c6a27b.png)

**Comment by vyleung** [comment] 2022-05-27 08:32
thanks for sharing, @nhan000! i'll close this issue, but feel free to re-open it if you still face the same issue @brunomiguel

**Closed as completed by vyleung** 2022-05-27 08:32 UTC
Labels: bug
